[config.wallpaper]
command = 'swww'
arguments = ['img']
set = true

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.niri]
input_path = '~/.config/matugen/templates/config.kdl'
output_path = '~/.config/niri/layout.kdl'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qt6ct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

