[colors.primary]
background = "{{colors.surface.default.hex}}"
foreground = "{{colors.on_surface.default.hex}}"

[colors.normal]
black   = "{{colors.surface_container.default.hex}}"        # color0
red     = "{{colors.error.default.hex}}"                    # color1
green   = "{{colors.secondary.default.hex}}"                # color2
yellow  = "{{colors.tertiary.default.hex}}"                 # color3
blue    = "{{colors.primary.default.hex}}"                  # color4
magenta = "{{colors.secondary_container.default.hex}}"      # color5
cyan    = "{{colors.primary_fixed_dim.default.hex}}"        # color6
white   = "{{colors.on_surface_variant.default.hex}}"       # color7

[colors.bright]
black   = "{{colors.surface_variant.default.hex}}"          # color8
red     = "{{colors.error_container.default.hex}}"          # color9
green   = "{{colors.on_secondary_container.default.hex}}"   # color10
yellow  = "{{colors.on_tertiary_container.default.hex}}"    # color11
blue    = "{{colors.on_primary_container.default.hex}}"     # color12
magenta = "{{colors.on_secondary.default.hex}}"             # color13
cyan    = "{{colors.on_primary_fixed.default.hex}}"         # color14
white   = "{{colors.on_surface.default.hex}}"               # color15
